"""
Unit & Integration Tests — Phase 7 Repository Intelligence
"""

import os
import sys
import time
import hashlib
import pytest
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from schemas.analysis_unit import AnalysisUnit, AnalysisUnitType, PriorityLevel
from schemas.security_surface import SecuritySurface, SecurityAsset, Countermeasure, TrustBoundary, EntryPoint, AttackerCapability
from schemas.file_classification import FileClassificationType, FileClassificationRecord
from schemas.repository_intelligence import (
    ExtendedRepositorySnapshot, BuildTarget, SymbolEntity,
    DependencyRelation, DependencyType, ReachabilityStatus, HW_SW_Contract,
    SecretQuarantineRecord, ContextExpansionRecord,
)
from repository_intelligence.scanner import RepositoryTreeScanner
from repository_intelligence.classifier import FileClassifier
from repository_intelligence.build_system import BuildSystemIndexer
from repository_intelligence.symbol_extractor import SymbolExtractor
from repository_intelligence.dependency_graph import DependencyGraphEngine
from repository_intelligence.security_surface_builder import SecuritySurfaceBuilder
from repository_intelligence.analysis_unit_builder import AnalysisUnitBuilder
from repository_intelligence.relevance import RelevanceEngine
from repository_intelligence.context import AgentContextGenerator
from repository_intelligence.service import RepositoryIntelligenceService
from history.database import DatabaseService
from history.repositories import AnalysisUnitRepository, ExtendedRepositorySnapshotRepository


# ─── Fixtures ────────────────────────────────────────────────────────────────

@pytest.fixture
def db():
    return DatabaseService(":memory:")


@pytest.fixture
def repo_fixture(tmp_path):
    """
    Creates a realistic multi-language repo fixture with:
    - C source files
    - Python files
    - RTL SystemVerilog
    - HJSON register descriptions
    - Bazel BUILD file
    - A test file
    - A vendor directory
    - A generated file
    - A secret file
    - An internal symlink
    """
    # Python source
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("def privilege_gate(user):\n    return user.is_admin\n")
    (tmp_path / "src" / "access_control.py").write_text("from main import privilege_gate\ndef check():\n    pass\n")

    # C source
    (tmp_path / "src" / "ctrl.c").write_text("int lock_bit_check(int val) { return val & 0x1; }\n")
    (tmp_path / "src" / "ctrl.h").write_text("#include <stdint.h>\nint lock_bit_check(int val);\n")

    # RTL SystemVerilog
    (tmp_path / "rtl").mkdir()
    (tmp_path / "rtl" / "sec_ctrl.sv").write_text(
        "module sec_ctrl(\n"
        "  input logic clk, rst,\n"
        "  input logic priv_en,\n"
        "  output logic lock_bit\n"
        ");\n"
        "always_ff @(posedge clk) begin\n"
        "  if (!rst) lock_bit <= 0;\n"
        "end\nendmodule\n"
    )

    # HJSON register description
    (tmp_path / "hw").mkdir()
    (tmp_path / "hw" / "sec_ctrl.hjson").write_text(
        '{ name: "SEC_CTRL_PRIV", registers: [ { name: "PRIV_LOCK", swaccess: "rw" } ] }'
    )

    # Bazel BUILD
    (tmp_path / "BUILD.bazel").write_text(
        'cc_library(\n  name = "sec_ctrl",\n  srcs = ["src/ctrl.c"],\n  hdrs = ["src/ctrl.h"],\n)\n'
    )

    # Test file
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_ctrl.py").write_text("def test_lock(): pass\n")

    # Vendor directory
    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "third_party_lib.c").write_text("// third party\n")

    # Generated file
    (tmp_path / "gen").mkdir()
    (tmp_path / "gen" / "sec_ctrl_regs.h").write_text(
        "// DO NOT EDIT — Autogenerated by regtool\n#define SEC_CTRL_PRIV 0x1234\n"
    )

    # Secret file
    (tmp_path / "secrets" ).mkdir()
    (tmp_path / "secrets" / "api_key.txt").write_text("api_key='mock_dummy_secret_key_1234567890'\n")

    # Internal symlink
    (tmp_path / "link_to_src").symlink_to(tmp_path / "src")

    return tmp_path


# ─── Layer 1: Snapshot & Identity ─────────────────────────────────────────────

def test_repository_snapshot_identity(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    snap = svc.scan_repository(str(repo_fixture))
    assert snap.archive_hash.startswith("archive-")
    assert len(snap.archive_hash) > 10


def test_per_file_hashes(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    # Every non-symlink file should have a content hash
    for rec in svc._file_records:
        if not rec.is_symlink and rec.size_bytes > 0:
            assert rec.content_hash and rec.content_hash != "", f"Missing hash for {rec.rel_path}"


def test_incremental_snapshot_detection(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    snap1 = svc.scan_repository(str(repo_fixture))

    # Modify one file
    (repo_fixture / "src" / "main.py").write_text("def privilege_gate(user):\n    return False  # modified\n")

    svc2 = RepositoryIntelligenceService(db)
    snap2 = svc2.scan_repository(str(repo_fixture))

    diff = svc2.diff_snapshots(snap1, snap2)
    assert diff["archive_hash_changed"] is True
    assert "src/main.py" in diff["modified_files"]


# ─── Layer 2: File Classification ─────────────────────────────────────────────

def test_file_classification(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))

    class_map = {r.rel_path: r.classification for r in svc._file_records}
    assert class_map.get("src/main.py") == FileClassificationType.PRIMARY_SOURCE
    assert class_map.get("tests/test_ctrl.py") == FileClassificationType.TEST


def test_generated_code_classification(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    gen_files = [r for r in svc._file_records if r.classification == FileClassificationType.GENERATED]
    assert len(gen_files) >= 1
    assert any("gen" in r.rel_path for r in gen_files)


def test_vendor_classification(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    vendor_files = [r for r in svc._file_records if r.classification == FileClassificationType.VENDOR]
    assert len(vendor_files) >= 1
    assert any("vendor" in r.rel_path for r in vendor_files)


# ─── Layer 3: Build System Intelligence ──────────────────────────────────────

def test_build_metadata_detection(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    snap = svc.scan_repository(str(repo_fixture))
    assert "Bazel" in snap.build_systems


def test_bazel_target_extraction(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    bazel_targets = [bt for bt in svc._build_targets if bt.build_system == "Bazel"]
    assert len(bazel_targets) >= 1
    assert any("sec_ctrl" in bt.target_name for bt in bazel_targets)


def test_hjson_security_metadata_detection(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    assert len(svc._contracts) >= 1
    assert any("PRIV_LOCK" in c.register_name or "SEC_CTRL" in c.register_name for c in svc._contracts)


# ─── Symlink Safety ──────────────────────────────────────────────────────────

def test_symlink_detection(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    # Internal symlink should be detected
    assert repo_fixture.joinpath("link_to_src").is_symlink()


def test_external_symlink_blocking(tmp_path, db):
    repo = tmp_path / "ext_sym_repo"
    repo.mkdir()
    (repo / "main.py").write_text("print('hello')\n")
    # Create an external symlink pointing to /etc/passwd
    ext_link = repo / "evil_link"
    try:
        ext_link.symlink_to("/etc/passwd")
    except Exception:
        pytest.skip("Cannot create external symlink on this system")

    svc = RepositoryIntelligenceService(db)
    snap = svc.scan_repository(str(repo))
    assert snap.symlink_summary.get("external_blocked", 0) >= 1


# ─── Secret Quarantine ───────────────────────────────────────────────────────

def test_secret_quarantine(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    assert len(svc._secrets) >= 1
    assert all("api_key" in s.file_path or s.secret_type for s in svc._secrets)


def test_secrets_not_in_agent_context(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx = svc.build_agent_context(units[0], [], [])
    all_included = " ".join(ctx.get("included_files", []))
    # Secret file path must never appear in agent context
    assert "secrets/api_key.txt" not in all_included


# ─── Symbol Extraction ───────────────────────────────────────────────────────

def test_cpp_symbol_extraction(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    c_fns = [s for s in svc._symbols if s.language in ("c", "cpp") and s.kind == "function"]
    assert any("lock_bit_check" in s.name for s in c_fns)


def test_python_structure_extraction(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    py_fns = [s for s in svc._symbols if s.language == "python" and s.kind == "function"]
    assert any("privilege_gate" in s.name for s in py_fns)


def test_rtl_module_extraction(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    rtl_mods = [s for s in svc._symbols if s.kind == "module" and s.language == "rtl"]
    assert any("sec_ctrl" in s.name for s in rtl_mods)


def test_go_structure_extraction(tmp_path, db):
    go_file = tmp_path / "handler.go"
    go_file.write_text("package main\n\ntype TokenValidator interface {\n    Validate()\n}\n\nfunc HandleRequest(w ResponseWriter, r *Request) {\n    return\n}\n")
    rec = FileClassificationRecord(
        rel_path="handler.go",
        abs_path=str(go_file),
        content_hash="abc",
        classification=FileClassificationType.PRIMARY_SOURCE,
        language="go",
        size_bytes=len(go_file.read_text())
    )
    syms = SymbolExtractor.extract_symbols([rec], str(tmp_path))
    assert any(s.name == "HandleRequest" and s.kind == "function" and s.language == "go" for s in syms)
    assert any(s.name == "TokenValidator" and s.kind == "interface" and s.language == "go" for s in syms)


def test_java_structure_extraction(tmp_path, db):
    java_file = tmp_path / "SecurityService.java"
    java_file.write_text("package com.sec;\n\npublic class SecurityService {\n    public void authenticate() {}\n}\n")
    rec = FileClassificationRecord(
        rel_path="SecurityService.java",
        abs_path=str(java_file),
        content_hash="def",
        classification=FileClassificationType.PRIMARY_SOURCE,
        language="java",
        size_bytes=len(java_file.read_text())
    )
    syms = SymbolExtractor.extract_symbols([rec], str(tmp_path))
    assert any(s.name == "SecurityService" and s.kind == "class" and s.language == "java" for s in syms)
    assert any(s.name == "authenticate" and s.kind == "method" and s.language == "java" for s in syms)


# ─── Dependency Graph & Reachability ─────────────────────────────────────────

def test_dependency_graph(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    # access_control.py imports from main.py
    assert len(svc._dependencies) >= 0  # may be 0 in minimal fixture


def test_reachability_hints(repo_fixture, db):
    files = [FileClassificationRecord(rel_path="src/main.py", abs_path="src/main.py", content_hash="abc", classification=FileClassificationType.PRIMARY_SOURCE, language="python", size_bytes=50)]
    deps = [DependencyRelation(source_id="src/access_control.py", target_id="src/main.py", relation_type=DependencyType.DIRECT, confidence=1.0, provenance="test")]
    r = DependencyGraphEngine.compute_reachability("src/main.py", ["src/access_control.py"], deps)
    assert r in (ReachabilityStatus.REACHABLE, ReachabilityStatus.LIKELY_REACHABLE)


# ─── Security Surface ─────────────────────────────────────────────────────────

def test_security_surface_creation(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    surf = svc.get_security_surface()
    assert surf is not None
    assert isinstance(surf, SecuritySurface)


def test_hw_sw_contract_detection(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    assert len(svc._contracts) >= 1
    c = svc._contracts[0]
    assert c.hjson_ref is not None


# ─── AnalysisUnit Construction ────────────────────────────────────────────────

def test_analysis_unit_creation(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    assert len(units) >= 1


def test_analysis_unit_not_equal_file(repo_fixture, db):
    """An AnalysisUnit must NOT simply equal a single file — it represents a meaningful boundary."""
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    for u in units:
        # Unit must have a name and type, not just one raw file path
        assert u.name and len(u.name) > 0
        assert u.unit_type in [e for e in AnalysisUnitType]
        # Unit must not have source_files count matching total repo files (it's scoped)
        assert len(u.source_files) < svc._snapshot.file_count


def test_analysis_unit_boundary_integrity(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    for u in units:
        assert u.snapshot_id == svc._snapshot.snapshot_id
        assert u.repository_id == svc._snapshot.repository_id


# ─── Relevance Engine ────────────────────────────────────────────────────────

def test_relevance_scoring(db):
    unit = AnalysisUnit(
        repository_id="r1", snapshot_id="s1",
        name="Test Unit", domain="rtl",
        trust_boundaries=["hw_boundary"],
        assets=["PRIV_REGISTER"],
        entry_points=["bus_interface"],
        security_properties=["lock_before_write"],
        countermeasures=["lock_bit"]
    )
    scored, reasons = RelevanceEngine.score_unit(unit)
    assert scored.relevance_score > 0.0
    assert len(reasons) >= 1


def test_priority_assignment(db):
    high_unit = AnalysisUnit(
        repository_id="r1", snapshot_id="s1",
        name="Critical Unit", domain="rtl",
        trust_boundaries=["boundary"],
        assets=["key"],
        security_properties=["prop"],
        entry_points=["entry"],
        countermeasures=["cm"]
    )
    scored, _ = RelevanceEngine.score_unit(high_unit)
    assert scored.priority in (PriorityLevel.CRITICAL, PriorityLevel.HIGH, PriorityLevel.MEDIUM)


# ─── Context Generation ───────────────────────────────────────────────────────

def test_agent_context_scoping(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx = svc.build_agent_context(units[0], [], ["lock_bit_missing"])
    assert "analysis_unit_id" in ctx
    assert "included_files" in ctx
    assert "security_surface_summary" in ctx
    # Verify it's scoped and not the entire repository
    assert len(ctx["included_files"]) < svc._snapshot.file_count


def test_vendor_not_sent_by_default(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx = svc.build_agent_context(units[0], [], [])
    all_included = " ".join(ctx.get("included_files", []))
    assert "vendor/" not in all_included


def test_generated_not_sent_by_default(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx = svc.build_agent_context(units[0], [], [])
    all_included = " ".join(ctx.get("included_files", []))
    assert "gen/sec_ctrl_regs.h" not in all_included


def test_one_hop_context_expansion(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx_no_expand = svc.build_agent_context(units[0], [], [], expand_hops=0)
    ctx_expanded = svc.build_agent_context(units[0], [], [], expand_hops=1, expansion_reason="Test 1-hop expansion")
    # Expansion is recorded in provenance
    assert ctx_expanded is not None


def test_context_expansion_audit(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    if not units:
        return
    ctx = svc.build_agent_context(
        units[0], [], [], expand_hops=1,
        expansion_reason="dependency on ctrl.h",
        requesting_agent_id="agent-agy-01"
    )
    # expansion field should be None or a dict with reason
    exp = ctx.get("expansion")
    if exp:
        assert "reason" in exp or exp is None


# ─── Phase 6 Memory Integration ──────────────────────────────────────────────

def test_phase6_memory_integration(repo_fixture, db):
    from memory.service import MemoryService
    from memory.promotion import PromotionEngine
    from schemas.memory import ResearchOutcomeRecord, PatternDomain, MemoryConfidence

    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))

    # Promote a pattern from scan findings
    prom_engine = PromotionEngine(db)
    outcome = ResearchOutcomeRecord(
        project_id="proj-fixture",
        task_id="t-fixture",
        run_id="r-fixture",
        domain=PatternDomain.RTL,
        hypothesis="Privilege register write without prior lock bit assertion in sec_ctrl module",
        confidence=MemoryConfidence.VALIDATED,
        is_generalizable=True
    )
    prom = prom_engine.evaluate_and_promote(outcome, "RTL Privilege Lock Pattern", ["lock_bit"], ["sec_ctrl"])
    assert prom.accepted is True

    # Retrieve against AnalysisUnit scope
    mem_svc = MemoryService(db)
    units = svc.get_analysis_units()
    if units:
        results = mem_svc.retrieve(
            project_id="proj-fixture-B",
            domain=PatternDomain.RTL,
            target_context="sec_ctrl lock_bit privilege register",
            scoped_indicators=["lock_bit"]
        )
        assert len(results) >= 1


# ─── Snapshot Diff ────────────────────────────────────────────────────────────

def test_snapshot_diff_signals(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    snap1 = svc.scan_repository(str(repo_fixture))

    (repo_fixture / "src" / "new_module.py").write_text("def new_fn(): pass\n")
    (repo_fixture / "src" / "main.py").write_text("# modified\n")

    svc2 = RepositoryIntelligenceService(db)
    snap2 = svc2.scan_repository(str(repo_fixture))

    diff = svc2.diff_snapshots(snap1, snap2)
    assert "src/new_module.py" in diff["new_files"]
    assert "src/main.py" in diff["modified_files"]
    assert diff["unchanged_files_count"] >= 0


# ─── Provenance ───────────────────────────────────────────────────────────────

def test_repository_intelligence_provenance(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    for u in units:
        assert "extractor" in u.provenance or "method" in u.provenance or "relevance_reasons" in u.provenance


# ─── Hard-Negative Test ───────────────────────────────────────────────────────

def test_hard_negative_no_vulnerability_from_ranking(repo_fixture, db):
    """
    Hard-negative: even CRITICAL priority AnalysisUnit must NOT be auto-declared vulnerable.
    Priority = investigation resource allocation, NOT vulnerability confirmation.
    """
    svc = RepositoryIntelligenceService(db)
    svc.scan_repository(str(repo_fixture))
    units = svc.get_analysis_units()
    for u in units:
        # No unit should be auto-marked as a vulnerability
        assert "VULNERABLE" not in u.description.upper()
        assert "CONFIRMED" not in u.classification.upper()


# ─── Performance ─────────────────────────────────────────────────────────────

def test_scan_performance(repo_fixture, db):
    svc = RepositoryIntelligenceService(db)
    t0 = time.time()
    snap = svc.scan_repository(str(repo_fixture))
    elapsed = time.time() - t0
    assert elapsed < 30.0, f"Scan took {elapsed:.1f}s — too slow for test fixture"
    print(f"\n[PERF] scan_time={elapsed:.3f}s  files={snap.file_count}  units={len(svc._analysis_units)}")


# ─── Phase 5 Regression ───────────────────────────────────────────────────────

def test_phase5_failover_regression(repo_fixture, db):
    from orchestrator.investigation import InvestigationWorkflow
    wf = InvestigationWorkflow(
        repo_path=str(repo_fixture),
        target_component="src",
        testing_config={"simulate_quota_exhaustion_for": ["agent-agy-01"]},
        db_service=db
    )
    result = wf.run()
    assert result.get("task_status") == "READY_FOR_REVIEW"
    # Failover should have replaced agent-agy-01
    selected = result.get("selected_agents", [])
    assert len(selected) >= 1


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
