"""
LLMorch Repository Intelligence - File Classifier (Phase 7)
Provides deterministic classification of repository files into explicit structural categories.
"""

import os
import re
from pathlib import Path
from typing import Tuple, List, Optional
from schemas.file_classification import FileClassificationType, FileClassificationRecord


class FileClassifier:
    """
    Deterministic File Classification Engine.
    Uses file extensions, directory roles, file contents, generator headers,
    vendor patterns, and secret signatures to categorize every file.
    """

    SECRET_PATTERNS = [
        (re.compile(r'-----BEGIN\s+([A-Za-z0-9_\-\s]+)?KEY-----', re.IGNORECASE), "PRIVATE_KEY"),
        (re.compile(r'-----BEGIN\s+CERTIFICATE-----', re.IGNORECASE), "CERTIFICATE"),
        (re.compile(r'api[_-]?key\s*[:=]\s*[\'"][A-Za-z0-9_\-]{16,}[\'"]', re.IGNORECASE), "API_KEY"),
        (re.compile(r'bearer\s+[A-Za-z0-9\-\._~\+\/]+=*', re.IGNORECASE), "TOKEN"),
        (re.compile(r'password\s*[:=]\s*[\'"][^\'"]{6,}[\'"]', re.IGNORECASE), "PASSWORD"),
        (re.compile(r'secret[_-]?key\s*[:=]\s*[\'"][A-Za-z0-9_\-]{16,}[\'"]', re.IGNORECASE), "SECRET_KEY"),
    ]

    GENERATED_MARKERS = [
        re.compile(r'@generated', re.IGNORECASE),
        re.compile(r'DO NOT EDIT', re.IGNORECASE),
        re.compile(r'Autogenerated by', re.IGNORECASE),
        re.compile(r'This file was generated', re.IGNORECASE),
    ]

    LANGUAGE_EXTENSIONS = {
        ".c": "c", ".h": "c", ".cpp": "cpp", ".hpp": "cpp", ".cc": "cpp", ".cxx": "cpp",
        ".go": "go", ".java": "java", ".py": "python", ".rs": "rust",
        ".v": "verilog", ".sv": "systemverilog", ".svh": "systemverilog", ".sva": "sva",
        ".s": "assembly", ".asm": "assembly", ".js": "javascript", ".ts": "typescript"
    }

    BUILD_METADATA_FILES = {
        "BUILD", "BUILD.bazel", "WORKSPACE", "MODULE.bazel", "CMakeLists.txt",
        "Makefile", "makefile", "Cargo.toml", "go.mod", "go.sum", "pom.xml",
        "build.gradle", "pyproject.toml", "setup.py"
    }

    SECURITY_METADATA_EXTS = {".hjson", ".json", ".yaml", ".yml"}

    @classmethod
    def classify_file(cls, abs_path: str, repo_root: str) -> FileClassificationRecord:
        rel_path = os.path.relpath(abs_path, repo_root) if abs_path.startswith(repo_root) else abs_path
        path_obj = Path(rel_path)
        parts = path_obj.parts
        name = path_obj.name
        suffix = path_obj.suffix.lower()

        # Size & Existence Check
        size = 0
        if os.path.exists(abs_path) and os.path.isfile(abs_path):
            size = os.path.getsize(abs_path)

        # Check Symlink
        is_symlink = os.path.islink(abs_path)

        # Language Detection
        language = cls.LANGUAGE_EXTENSIONS.get(suffix, "unknown")
        if name in cls.BUILD_METADATA_FILES or suffix == ".core":
            language = "build_system"

        # Content Inspection (Secret detection & Generated headers)
        is_secret = False
        secret_type = None
        is_generated = False

        if size > 0 and size < 1_000_000 and not is_symlink:
            try:
                with open(abs_path, "r", encoding="utf-8", errors="ignore") as f:
                    content_head = f.read(4096)

                # Secret Scan
                for pat, stype in cls.SECRET_PATTERNS:
                    if pat.search(content_head):
                        is_secret = True
                        secret_type = stype
                        break

                # Generated Code Scan
                for pat in cls.GENERATED_MARKERS:
                    if pat.search(content_head):
                        is_generated = True
                        break
            except Exception:
                pass

        if is_secret:
            return FileClassificationRecord(
                rel_path=rel_path,
                abs_path=abs_path,
                content_hash="",
                classification=FileClassificationType.SECRET,
                language=language,
                size_bytes=size,
                is_symlink=is_symlink,
                is_secret=True
            )

        # Build / Cache / Noise directory checks
        low_parts = [p.lower() for p in parts]
        if any(p in {".git", "node_modules", "__pycache__", ".pytest_cache", "build", "dist", ".bazel-out", "bazel-out"} for p in low_parts):
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.CACHE if "cache" in rel_path.lower() else FileClassificationType.BUILD_OUTPUT,
                language=language, size_bytes=size, is_symlink=is_symlink
            )

        # Vendor / Third Party Check
        if any(p in {"third_party", "vendor", "deps", "external"} for p in low_parts[:-1]):
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.VENDOR,
                language=language, size_bytes=size, is_symlink=is_symlink
            )

        # Generated Code Check
        if is_generated or "generated" in rel_path.lower():
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.GENERATED,
                language=language, size_bytes=size, is_symlink=is_symlink
            )

        # Build Metadata Check
        if name in cls.BUILD_METADATA_FILES or suffix in {".bzl", ".core", ".cmake"}:
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.BUILD_METADATA,
                language="build_system", size_bytes=size, is_symlink=is_symlink
            )

        # Security Metadata Check (e.g. HJSON register files, testplans)
        if suffix in cls.SECURITY_METADATA_EXTS and ("reg" in rel_path.lower() or "sec" in rel_path.lower() or "testplan" in rel_path.lower()):
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.SECURITY_METADATA,
                language="metadata", size_bytes=size, is_symlink=is_symlink
            )

        # Test & Formal Check
        if any(p in {"test", "tests", "testing"} for p in low_parts) or name.startswith("test_") or name.endswith("_test.go") or name.endswith("_test.py") or suffix == ".sva":
            cls_type = FileClassificationType.FORMAL if suffix == ".sva" or "formal" in rel_path.lower() else FileClassificationType.TEST
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=cls_type, language=language, size_bytes=size, is_symlink=is_symlink
            )

        # Documentation Check
        if suffix in {".md", ".rst", ".txt", ".pdf"} or "doc" in low_parts:
            return FileClassificationRecord(
                rel_path=rel_path, abs_path=abs_path, content_hash="",
                classification=FileClassificationType.DOCUMENTATION,
                language="markdown" if suffix == ".md" else "text", size_bytes=size, is_symlink=is_symlink
            )

        # Default Primary Source
        return FileClassificationRecord(
            rel_path=rel_path, abs_path=abs_path, content_hash="",
            classification=FileClassificationType.PRIMARY_SOURCE,
            language=language, size_bytes=size, is_symlink=is_symlink
        )
